In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/competitions/playground-series-s6e3/sample_submission.csv
/kaggle/input/competitions/playground-series-s6e3/train.csv
/kaggle/input/competitions/playground-series-s6e3/test.csv

In [2]:
import pandas as pd

try:
    train_df = pd.read_csv('/kaggle/input/playground-series-s6e3/train.csv')
    test_df = pd.read_csv('/kaggle/input/playground-series-s6e3/test.csv')
    sample_submission_df = pd.read_csv('/kaggle/input/playground-series-s6e3/sample_submission.csv')
    print("Datasets loaded successfully.")
except FileNotFoundError as e:
    print(f"Error loading file: {e}")
    train_df = test_df = sample_submission_df = None

if train_df is not None:
    print("\n--- Training Data Head ---")
    display(train_df.head())

    print("\n--- Training Data Info ---")
    train_df.info()

    print("\n--- Training Data Description ---")
    display(train_df.describe(include='all'))

if test_df is not None:
    print("\n--- Test Data Head ---")
    display(test_df.head())

if sample_submission_df is not None:
    print("\n--- Sample Submission Head ---")
    display(sample_submission_df.head())

Error loading file: [Errno 2] No such file or directory: '/kaggle/input/playground-series-s6e3/train.csv'

In [3]:
import os

# See all available input data
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

/kaggle/input/competitions/playground-series-s6e3/sample_submission.csv
/kaggle/input/competitions/playground-series-s6e3/train.csv
/kaggle/input/competitions/playground-series-s6e3/test.csv

In [4]:
import pandas as pd

try:
    train_df = pd.read_csv('/kaggle/input/competitions/playground-series-s6e3/train.csv')
    test_df = pd.read_csv('/kaggle/input/competitions/playground-series-s6e3/test.csv')
    sample_submission_df = pd.read_csv('/kaggle/input/competitions/playground-series-s6e3/sample_submission.csv')
    print("Datasets loaded successfully.")
except FileNotFoundError as e:
    print(f"Error loading file: {e}")
    train_df = test_df = sample_submission_df = None

if train_df is not None:
    print("\n--- Training Data Head ---")
    display(train_df.head())

    print("\n--- Training Data Info ---")
    train_df.info()

    print("\n--- Training Data Description ---")
    display(train_df.describe(include='all'))

if test_df is not None:
    print("\n--- Test Data Head ---")
    display(test_df.head())

if sample_submission_df is not None:
    print("\n--- Sample Submission Head ---")
    display(sample_submission_df.head())

Datasets loaded successfully.

--- Training Data Head ---

,id,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,0,Male,0,Yes,Yes,29,Yes,No,DSL,Yes,...,Yes,Yes,No,No,One year,Yes,Mailed check,60.10,1653.85,No
1,1,Male,0,Yes,Yes,58,Yes,No,DSL,Yes,...,No,Yes,Yes,No,Two year,No,Credit card (automatic),69.50,3778.20,No
2,2,Male,0,Yes,No,58,Yes,Yes,Fiber optic,No,...,No,No,Yes,Yes,Month-to-month,Yes,Electronic check,100.40,5841.35,No
3,3,Female,0,No,No,1,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,69.70,70.70,Yes
4,4,Female,0,No,No,1,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.45,70.45,Yes

--- Training Data Info ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 594194 entries, 0 to 594193
Data columns (total 21 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   id                594194 non-null  int64
 1   gender            594194 non-null  object
 2   SeniorCitizen     594194 non-null  int64
 3   Partner           594194 non-null  object
 4   Dependents        594194 non-null  object
 5   tenure            594194 non-null  int64
 6   PhoneService      594194 non-null  object
 7   MultipleLines     594194 non-null  object
 8   InternetService   594194 non-null  object
 9   OnlineSecurity    594194 non-null  object
 10  OnlineBackup      594194 non-null  object
 11  DeviceProtection  594194 non-null  object
 12  TechSupport       594194 non-null  object
 13  StreamingTV       594194 non-null  object
 14  StreamingMovies   594194 non-null  object
 15  Contract          594194 non-null  object
 16  PaperlessBilling  594194 non-null  object
 17  PaymentMethod     594194 non-null  object
 18  MonthlyCharges    594194 non-null  float64
 19  TotalCharges      594194 non-null  float64
 20  Churn             594194 non-null  object
dtypes: float64(2), int64(3), object(16)
memory usage: 95.2+ MB

--- Training Data Description ---

,id,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
count,594194.000000,594194,594194.000000,594194,594194,594194.000000,594194,594194,594194,594194,...,594194,594194,594194,594194,594194,594194,594194,594194.000000,594194.000000,594194
unique,NaN,2,NaN,2,2,NaN,2,3,3,3,...,3,3,3,3,3,2,4,NaN,NaN,2
top,NaN,Female,NaN,Yes,No,NaN,Yes,No,Fiber optic,No,...,No,No,Yes,Yes,Month-to-month,Yes,Electronic check,NaN,NaN,No
freq,NaN,298738,NaN,309554,414362,NaN,557893,283384,272386,289474,...,247377,288571,240301,241435,298918,365579,215372,NaN,NaN,460377
mean,297096.500000,NaN,0.114102,NaN,NaN,36.577258,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,65.866223,2494.377057,NaN
std,171529.177262,NaN,0.317936,NaN,NaN,25.061922,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,31.067444,2353.916710,NaN
min,0.000000,NaN,0.000000,NaN,NaN,1.000000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18.250000,18.800000,NaN
25%,148548.250000,NaN,0.000000,NaN,NaN,12.000000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,29.900000,639.650000,NaN
50%,297096.500000,NaN,0.000000,NaN,NaN,35.000000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,74.100000,1433.650000,NaN
75%,445644.750000,NaN,0.000000,NaN,NaN,62.000000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,90.800000,4263.800000,NaN
max,594193.000000,NaN,1.000000,NaN,NaN,72.000000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,118.750000,8684.800000,NaN

--- Test Data Head ---

,id,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges
0,594194,Female,0,Yes,No,72,Yes,Yes,Fiber optic,Yes,Yes,Yes,Yes,Yes,Yes,Two year,Yes,Electronic check,115.55,8061.50
1,594195,Female,0,Yes,No,71,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Bank transfer (automatic),19.80,1336.50
2,594196,Male,0,No,No,12,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Bank transfer (automatic),55.55,633.55
3,594197,Male,0,Yes,Yes,71,Yes,Yes,DSL,Yes,No,Yes,Yes,Yes,Yes,Two year,No,Credit card (automatic),84.10,6457.15
4,594198,Female,0,No,No,15,Yes,No,Fiber optic,Yes,No,No,No,Yes,Yes,Month-to-month,No,Electronic check,90.35,1233.65

--- Sample Submission Head ---

       id  Churn
0  594194      0
1  594195      0
2  594196      0
3  594197      0
4  594198      0

In [5]:
import numpy as np

BASE_PATH = '/kaggle/input/competitions/playground-series-s6e3'

def preprocess_totalcharges(df, label, median_fill=None):
    if 'TotalCharges' in df.columns:
        df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')
        null_count = df['TotalCharges'].isnull().sum()
        if null_count > 0:
            fill_value = median_fill if median_fill is not None else df['TotalCharges'].median()
            print(f"[{label}] Found {null_count} NaN(s) in 'TotalCharges'. Filling with median: {fill_value:.2f}")
            df['TotalCharges'] = df['TotalCharges'].fillna(fill_value)
        else:
            print(f"[{label}] 'TotalCharges' is clean, no NaNs found.")
    else:
        print(f"[{label}] 'TotalCharges' column not found.")
    return df

# --- Preprocess Train ---
print("\n--- Preprocessing Training Data ---")
train_df = preprocess_totalcharges(train_df, label='Train')

if 'Churn' in train_df.columns:
    train_df['Churn'] = train_df['Churn'].map({'No': 0, 'Yes': 1})
    print(f"Churn encoded. Value counts:\n{train_df['Churn'].value_counts()}")
else:
    print("'Churn' column not found in training data.")

print("\nUnique values for object columns in training data:")
for col in train_df.select_dtypes(include='object').columns:
    print(f"  {col}: {train_df[col].unique()}")

# --- Preprocess Test ---
print("\n--- Preprocessing Test Data ---")
train_median = train_df['TotalCharges'].median() if 'TotalCharges' in train_df.columns else None
test_df = preprocess_totalcharges(test_df, label='Test', median_fill=train_median)

print("\nUnique values for object columns in test data:")
for col in test_df.select_dtypes(include='object').columns:
    print(f"  {col}: {test_df[col].unique()}")

# --- Final Info ---
print("\n--- Training Data Info After Preprocessing ---")
train_df.info()
print("\n--- Test Data Info After Preprocessing ---")
test_df.info()

--- Preprocessing Training Data ---
[Train] 'TotalCharges' is clean, no NaNs found.
Churn encoded. Value counts:
Churn
0    460377
1    133817
Name: count, dtype: int64

Unique values for object columns in training data:
  gender: ['Male' 'Female']
  Partner: ['Yes' 'No']
  Dependents: ['Yes' 'No']
  PhoneService: ['Yes' 'No']
  MultipleLines: ['No' 'Yes' 'No phone service']
  InternetService: ['DSL' 'Fiber optic' 'No']
  OnlineSecurity: ['Yes' 'No' 'No internet service']
  OnlineBackup: ['No' 'Yes' 'No internet service']
  DeviceProtection: ['Yes' 'No' 'No internet service']
  TechSupport: ['Yes' 'No' 'No internet service']
  StreamingTV: ['No' 'Yes' 'No internet service']
  StreamingMovies: ['No' 'Yes' 'No internet service']
  Contract: ['One year' 'Two year' 'Month-to-month']
  PaperlessBilling: ['Yes' 'No']
  PaymentMethod: ['Mailed check' 'Credit card (automatic)' 'Electronic check'
 'Bank transfer (automatic)']

--- Preprocessing Test Data ---
[Test] 'TotalCharges' is clean, no NaNs found.

Unique values for object columns in test data:
  gender: ['Female' 'Male']
  Partner: ['Yes' 'No']
  Dependents: ['No' 'Yes']
  PhoneService: ['Yes' 'No']
  MultipleLines: ['Yes' 'No' 'No phone service']
  InternetService: ['Fiber optic' 'No' 'DSL']
  OnlineSecurity: ['Yes' 'No internet service' 'No']
  OnlineBackup: ['Yes' 'No internet service' 'No']
  DeviceProtection: ['Yes' 'No internet service' 'No']
  TechSupport: ['Yes' 'No internet service' 'No']
  StreamingTV: ['Yes' 'No internet service' 'No']
  StreamingMovies: ['Yes' 'No internet service' 'No']
  Contract: ['Two year' 'Month-to-month' 'One year']
  PaperlessBilling: ['Yes' 'No']
  PaymentMethod: ['Electronic check' 'Bank transfer (automatic)' 'Credit card (automatic)'
 'Mailed check']

--- Training Data Info After Preprocessing ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 594194 entries, 0 to 594193
Data columns (total 21 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   id                594194 non-null  int64
 1   gender            594194 non-null  object
 2   SeniorCitizen     594194 non-null  int64
 3   Partner           594194 non-null  object
 4   Dependents        594194 non-null  object
 5   tenure            594194 non-null  int64
 6   PhoneService      594194 non-null  object
 7   MultipleLines     594194 non-null  object
 8   InternetService   594194 non-null  object
 9   OnlineSecurity    594194 non-null  object
 10  OnlineBackup      594194 non-null  object
 11  DeviceProtection  594194 non-null  object
 12  TechSupport       594194 non-null  object
 13  StreamingTV       594194 non-null  object
 14  StreamingMovies   594194 non-null  object
 15  Contract          594194 non-null  object
 16  PaperlessBilling  594194 non-null  object
 17  PaymentMethod     594194 non-null  object
 18  MonthlyCharges    594194 non-null  float64
 19  TotalCharges      594194 non-null  float64
 20  Churn             594194 non-null  int64
dtypes: float64(2), int64(4), object(15)
memory usage: 95.2+ MB

--- Test Data Info After Preprocessing ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 254655 entries, 0 to 254654
Data columns (total 20 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   id                254655 non-null  int64
 1   gender            254655 non-null  object
 2   SeniorCitizen     254655 non-null  int64
 3   Partner           254655 non-null  object
 4   Dependents        254655 non-null  object
 5   tenure            254655 non-null  int64
 6   PhoneService      254655 non-null  object
 7   MultipleLines     254655 non-null  object
 8   InternetService   254655 non-null  object
 9   OnlineSecurity    254655 non-null  object
 10  OnlineBackup      254655 non-null  object
 11  DeviceProtection  254655 non-null  object
 12  TechSupport       254655 non-null  object
 13  StreamingTV       254655 non-null  object
 14  StreamingMovies   254655 non-null  object
 15  Contract          254655 non-null  object
 16  PaperlessBilling  254655 non-null  object
 17  PaymentMethod     254655 non-null  object
 18  MonthlyCharges    254655 non-null  float64
 19  TotalCharges      254655 non-null  float64
dtypes: float64(2), int64(3), object(15)
memory usage: 38.9+ MB

In [6]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from imblearn.over_sampling import SMOTE

print("\n--- Feature Engineering & Encoding ---")

# Drop irrelevant columns
drop_cols = ['id', 'customerID'] 
drop_cols = [c for c in drop_cols if c in train_df.columns]  # only drop if they exist
train_df.drop(columns=drop_cols, inplace=True)

# Separate features and target
X = train_df.drop(columns=['Churn'])
y = train_df['Churn']

# Encode binary yes/no columns
binary_cols = [col for col in X.select_dtypes(include='object').columns
               if X[col].nunique() == 2]
for col in binary_cols:
    X[col] = LabelEncoder().fit_transform(X[col])
    print(f"  Label encoded: {col}")

# One-hot encode remaining categorical columns
X = pd.get_dummies(X, drop_first=True)
print(f"\nShape after encoding: {X.shape}")

# Align test_df with train features
test_df_proc = test_df.drop(columns=[c for c in drop_cols if c in test_df.columns], errors='ignore')
test_df_proc = pd.get_dummies(test_df_proc, drop_first=True)
test_df_proc = test_df_proc.reindex(columns=X.columns, fill_value=0)  # match train columns exactly
print(f"Test shape after alignment: {test_df_proc.shape}")

# --- Train / Validation Split ---
print("\n--- Train/Validation Split ---")
X_train, X_val, y_train, y_val = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)
print(f"X_train: {X_train.shape}, X_val: {X_val.shape}")
print(f"Churn rate in train: {y_train.mean():.3f} | val: {y_val.mean():.3f}")

# --- SMOTE Resampling ---
print("\n--- Applying SMOTE to Training Data ---")
print(f"Before SMOTE — Class counts: {y_train.value_counts().to_dict()}")

sm = SMOTE(random_state=42)
X_train_resampled, y_train_resampled = sm.fit_resample(X_train, y_train)

print(f"After SMOTE  — Class counts: {pd.Series(y_train_resampled).value_counts().to_dict()}")
print(f"X_train_resampled shape: {X_train_resampled.shape}")

--- Feature Engineering & Encoding ---
  Label encoded: gender
  Label encoded: Partner
  Label encoded: Dependents
  Label encoded: PhoneService
  Label encoded: PaperlessBilling

Shape after encoding: (594194, 30)
Test shape after alignment: (254655, 30)

--- Train/Validation Split ---
X_train: (475355, 30), X_val: (118839, 30)
Churn rate in train: 0.225 | val: 0.225

--- Applying SMOTE to Training Data ---
Before SMOTE — Class counts: {0: 368301, 1: 107054}
After SMOTE  — Class counts: {0: 368301, 1: 368301}
X_train_resampled shape: (736602, 30)

In [7]:
# Run this to see which models are available
models_to_check = ['best_xgb_model', 'final_rf_model', 'logistic_model']
for m in models_to_check:
    status = "✅ defined" if m in dir() else "❌ NOT defined"
    print(f"  {m}: {status}")

  best_xgb_model: ❌ NOT defined
  final_rf_model: ❌ NOT defined
  logistic_model: ❌ NOT defined

In [8]:
import xgboost as xgb

print("Training XGBoost with best known parameters...")

best_xgb_model = xgb.XGBClassifier(
    n_estimators=300,
    learning_rate=0.05,
    max_depth=6,
    subsample=0.8,
    colsample_bytree=0.8,
    gamma=0.1,
    reg_lambda=2.0,
    reg_alpha=0.5,
    objective='binary:logistic',
    eval_metric='logloss',
    random_state=42,
    n_jobs=-1,
    tree_method='hist',
    device='cpu'
)

best_xgb_model.fit(X_train_resampled, y_train_resampled)
print("✅ XGBoost trained.")

Training XGBoost with best known parameters...
✅ XGBoost trained.

In [9]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression

# Random Forest
print("Training Random Forest...")
final_rf_model = RandomForestClassifier(
    n_estimators=300,
    max_depth=8,
    min_samples_split=5,
    class_weight='balanced',
    random_state=42,
    n_jobs=-1
)
final_rf_model.fit(X_train_resampled, y_train_resampled)
print("✅ Random Forest trained.")

# Logistic Regression
print("Training Logistic Regression...")
logistic_model = LogisticRegression(
    C=0.1,
    max_iter=1000,
    class_weight='balanced',
    random_state=42,
    n_jobs=-1
)
logistic_model.fit(X_train_resampled, y_train_resampled)
print("✅ Logistic Regression trained.")

Training Random Forest...
✅ Random Forest trained.
Training Logistic Regression...
✅ Logistic Regression trained.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(